#!/bin/bash

#rm packer_virtualbox-iso_virtualbox.box || true
packer build -only=virtualbox-iso template.json
vagrant box remove nestbox || true
vagrant box add nestbox packer_virtualbox-iso_virtualbox.box
